FROM freqtradeorg/freqtrade:develop

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
USER root

RUN apt install build-essential -y

# The below dependency - pyti - serves as an example. Please use whatever you need!
RUN pip install --user cython
RUN pip install --user numpy
RUN pip install --user zigzag

# Switch back to user (only if you required root above)
USER ftuser


